name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python & Kivy-iOS
        run: |
          python3 -m pip install --upgrade pip
          pip install kivy-ios

      - name: Run iOS build script
        run: bash build_ios.sh

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp.ipa
          path: build/MyApp.ipa
